Resources:
  LambdaServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "lambda_${self:service.name}_${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "lambda_${self:service.name}_${self:provider.stage}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:*"
                  - "logs:*"
                  - "dbqms:*"
                  - "rds-data:*"
                  - "secretsmanager:*"
                  - "ec2:*"
                Resource:
                  - "*"
