Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - ServerlessSecurityGroup
    Properties:
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}
      MasterUserPassword: ${env:DB_PASSWORD}
      Port: ${env:DB_PORT}
      DBSubnetGroupName:
        Ref: ServerlessSubnetGroup
      Engine: aurora-postgresql
      EnableHttpEndpoint: true
      EngineVersion: '10.7'
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      DatabaseName: ${self:custom.AURORA.DB_NAME}
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName: 'default.aurora-postgresql10'
      VpcSecurityGroupIds:
        - !Ref 'ServerlessSecurityGroup'
