Resources:
  ElasticIpLambda:
     Type: AWS::EC2::EIP
     Properties:
       Domain: vpc
  ServerlessVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: ${self:custom.AURORA.VPC_CIDR}.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: 'Name'
          Value: 'ServerlessVPC'
  ServerlessVPCGA:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: ServerlessVPC
      InternetGatewayId:
        Ref: ServerlessInternetGateway
  NatGatewayLambda:
  Type: AWS::EC2::NatGateway
  Properties:
    AllocationId:
      Fn::GetAtt:
        - ElasticIpLambda
        - AllocationId
    SubnetId:
      Ref: ServerlessSubnetA
