Resources:

  RDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - ServerlessSecurityGroup
    Properties:
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}
      MasterUserPassword: ${env:DB_PASSWORD}
      DBSubnetGroupName:
        Ref: ServerlessSubnetGroup
      Engine: aurora
      EngineVersion: "5.6"
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      DatabaseName: ${self:custom.AURORA.DB_NAME}
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName:
        Ref: RDSClusterParameter
      VpcSecurityGroupIds:
        - !Ref "ServerlessSecurityGroup"
  RDSClusterParameter:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for the Serverless Aurora RDS DB.
      Family: aurora5.6
      Parameters:
        character_set_database: "utf32"
  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for the Serverless Aurora RDS DB.
      Family: aurora5.6
      Parameters:
        sql_mode: IGNORE_SPACE
        max_connections: 100
        wait_timeout: 900
        interactive_timeout: 900
Outputs:
  RDSHost:
    Description: Host of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Address]
  RDSPort:
    Description: Port of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Port]
