Resources:

  RDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - ServerlessSecurityGroup
    Properties:
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}
      MasterUserPassword: ${env:DB_PASSWORD}
      Port: ${env:DB_PORT}
      DBSubnetGroupName:
        Ref: ServerlessSubnetGroup
      Engine: aurora-postgresql
      EngineVersion: "10.7"
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      DatabaseName: ${self:custom.AURORA.DB_NAME}
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName: "default.aurora-postgresql10"
      VpcSecurityGroupIds:
        - !Ref "ServerlessSecurityGroup"
Outputs:
  RDSHost:
    Description: Host of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Address]
  RDSPort:
    Description: Port of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Port]
