Resources:

  RDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - ServerlessSecurityGroup
    Properties:
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}
      MasterUserPassword: ${env:DB_PASSWORD}
      Port: ${env:DB_PORT}
      DBSubnetGroupName:
        Ref: ServerlessSubnetGroup
      Engine: aurora-postgresql
      EngineVersion: "10.7"
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      DatabaseName: ${self:custom.AURORA.DB_NAME}
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName: "default.aurora-postgresql10"
      VpcSecurityGroupIds:
        - !Ref "ServerlessSecurityGroup"
  # RDSClusterParameter:
  #   Type: AWS::RDS::DBClusterParameterGroup
  #   Properties:
  #     Description: Parameter group for the Serverless Aurora RDS DB.
  #     Family: aurora-postgresql9.6
  #     Parameters:
  #       character_set_database: "UTF8"
  # RDSDBParameterGroup:
  #   Type: AWS::RDS::DBParameterGroup
  #   Properties:
  #     Description: Parameter group for the Serverless Aurora RDS DB.
  #     Family: aurora-postgresql9.6
  #     Parameters:
  #       sql_mode: IGNORE_SPACE
  #       max_connections: 100
  #       wait_timeout: 900
  #       interactive_timeout: 900
Outputs:
  RDSHost:
    Description: Host of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Address]
  RDSPort:
    Description: Port of the AppSync-RDS-todo RDS instance
    Value:
      Fn::GetAtt: [RDSCluster, Endpoint.Port]
