name: appsync-rds-todo CD develop
on:
  push:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: install dependencies
        run: npm i
      - name: Get branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}
      - name: Create envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
          file_name: .env.${{steps.vars.outputs.stage}}.local
      - name: serverless deploy --stage=develop
        run: npx serverless deploy --stage=develop --force
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
